export const ADD_ARTICLE = 'ADD_ARTICLE';
export const FETCH_DATA_STARTED = 'FETCH_DATA_STARTED';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

export const FETCH_APP_ENGINE_STARTED = 'FETCH_APP_ENGINE_STARTED';
export const FETCH_APP_ENGINE_SUCCESS = 'FETCH_APP_ENGINE_SUCCESS';
export const FETCH_APP_ENGINE_FAILURE = 'FETCH_APP_ENGINE_FAILURE';