export const ADD_ARTICLE = 'ADD_ARTICLE';
export const FETCH_DATA_STARTED = 'FETCH_DATA_STARTED';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

export const GET_APP_ENGINE_TABLE_STARTED = 'GET_APP_ENGINE_TABLE_STARTED';
export const GET_APP_ENGINE_TABLE_SUCCESS = 'GET_APP_ENGINE_TABLE_SUCCESS';
export const GET_APP_ENGINE_TABLE_FAILURE = 'GET_APP_ENGINE_TABLE_FAILURE';

export const POST_EXCEL_STARTED = 'POST_EXCEL_STARTED';
export const POST_EXCEL_SUCCESS = 'POST_EXCEL_SUCCESS';
export const POST_EXCEL_FAILURE = 'POST_EXCEL_FAILURE';

export const APP_ENGINE_CREATE_FOLDER_STARTED = 'APP_ENGINE_CREATE_FOLDER';
export const APP_ENGINE_CREATE_FOLDER_SUCCESS = 'APP_ENGINE_CREATE_FOLDER_SUCCESS';
export const APP_ENGINE_CREATE_FOLDER_FAILURE = 'APP_ENGINE_CREATE_FOLDER_FAILURE';

export const APP_ENGINE_CREATE_FILE_STARTED = 'APP_ENGINE_CREATE_FILE_STARTED';
export const APP_ENGINE_CREATE_FILE_SUCCESS = 'APP_ENGINE_CREATE_FILE_SUCCESS';
export const APP_ENGINE_CREATE_FILE_FAILURE = 'APP_ENGINE_CREATE_FILE_FAILURE';

export const GET_APP_ENGINE_USER_STARTED = 'GET_APP_ENGINE_USER_STARTED';
export const GET_APP_ENGINE_USER_SUCCESS = 'GET_APP_ENGINE_USER_SUCCESS';
export const GET_APP_ENGINE_USER_FAILURE = 'GET_APP_ENGINE_USER_FAILURE';